# Generated by Django 5.2.3 on 2025-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='templates/questions_image', verbose_name='Image of the question'),
        ),
    ]
