# Generated by Django 5.2.3 on 2025-07-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='no_of_question',
            field=models.IntegerField(verbose_name='How many questions this quiz have'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_duration',
            field=models.IntegerField(verbose_name='time duration in minutes'),
        ),
    ]
